defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:02d}_val_loss_{val_loss:.4f}_val_acc_{val_acc:.2f}"
  auto_insert_metric_name: False
  every_n_epochs: 1
  save_top_k: -1

model_summary:
  max_depth: -1
